"""PDF Generator for LLM Council reports."""

import io
import re
from typing import List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute total page count and draw header/footer."""
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Letter dimensions: 612 x 792
        width, height = letter
        margin = 54  # 0.75 in
        
        # Draw header (on all pages)
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#4a90e2"))
        self.drawString(margin, height - 40, "LLM COUNCIL")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6b7280"))
        self.drawRightString(width - margin, height - 40, "Synthesis Report")
        
        # Header rule line
        self.setStrokeColor(colors.HexColor("#e5e7eb"))
        self.setLineWidth(0.5)
        self.line(margin, height - 46, width - margin, height - 46)
        
        # Draw footer (on all pages)
        self.line(margin, 52, width - margin, 52)
        
        self.drawString(margin, 38, "Confidential - generated by LLM Council")
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(width - margin, 38, page_text)
        
        self.restoreState()


def clean_text_for_pdf(text: str) -> str:
    """Sanitize input text to be fully compatible with ReportLab's standard Helvetica font."""
    if not text:
        return ""
        
    replacements = {
        '\u201c': '"',      # Left double quote
        '\u201d': '"',      # Right double quote
        '\u2018': "'",      # Left single quote
        '\u2019': "'",      # Right single quote
        '\u2013': '-',      # En dash
        '\u2014': '-',      # Em dash
        '\u2022': '*',      # Bullet
        '\u2026': '...',    # Ellipsis
        '\u00a0': ' ',      # Non-breaking space
        '\u2192': '->',     # Right arrow
        '\u2190': '<-',     # Left arrow
        '\u2714': '[Yes]',  # Checkmark
        '\u2713': '[Yes]',  # Checkmark
        '\u2717': '[No]',   # Cross mark
    }
    
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
        
    # Keep printable ASCII and basic latin characters
    # Filter out emojis and other non-supported Unicode ranges
    cleaned_chars = []
    for char in text:
        cp = ord(char)
        # Allow standard ASCII, common Latin-1 Supplement (like accented letters)
        if cp < 128 or (160 <= cp <= 255):
            cleaned_chars.append(char)
        else:
            # Fallback for other characters
            cleaned_chars.append(' ')
            
    return "".join(cleaned_chars)


def escape_html_entities(text: str) -> str:
    """Escapes HTML special characters for ReportLab XML parser."""
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def convert_markdown_inline(text: str) -> str:
    """Convert basic inline Markdown (*, **, `) into ReportLab Paragraph HTML tags."""
    escaped = escape_html_entities(text)
    
    # 1. Bold: **text** -> <b>text</b>
    parts = escaped.split('**')
    bold_rendered = []
    for i, part in enumerate(parts):
        if i % 2 == 1:
            bold_rendered.append(f"<b>{part}</b>")
        else:
            bold_rendered.append(part)
    escaped = "".join(bold_rendered)
    
    # 2. Italic: *text* -> <i>text</i>
    parts = escaped.split('*')
    italic_rendered = []
    for i, part in enumerate(parts):
        if i % 2 == 1:
            italic_rendered.append(f"<i>{part}</i>")
        else:
            italic_rendered.append(part)
    escaped = "".join(italic_rendered)
    
    # 3. Inline code: `code` -> <font name="Courier" color="#d15a5a"><b>code</b></font>
    parts = escaped.split('`')
    code_rendered = []
    for i, part in enumerate(parts):
        if i % 2 == 1:
            code_rendered.append(f'<font name="Courier" size="9" color="#b32424"><b>{part}</b></font>')
        else:
            code_rendered.append(part)
    escaped = "".join(code_rendered)
    
    return escaped


def generate_pdf(title: str, content: str) -> io.BytesIO:
    """
    Generate a styled PDF from title and markdown content.
    Returns a BytesIO stream containing the generated PDF file.
    """
    buffer = io.BytesIO()
    
    # Page setup
    # Margins are 54pt (0.75 in). Content width: 612 - 108 = 504 pt.
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    # Styles
    base_styles = getSampleStyleSheet()
    
    # Custom styles
    styles = {
        'Title': ParagraphStyle(
            'ReportTitle',
            parent=base_styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1f2937"),
            spaceAfter=15,
            alignment=TA_LEFT
        ),
        'H1': ParagraphStyle(
            'Heading1',
            parent=base_styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=15,
            leading=19,
            textColor=colors.HexColor("#2563eb"),
            spaceBefore=16,
            spaceAfter=8,
            keepWithNext=True
        ),
        'H2': ParagraphStyle(
            'Heading2',
            parent=base_styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#1e40af"),
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True
        ),
        'H3': ParagraphStyle(
            'Heading3',
            parent=base_styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor("#1f2937"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        ),
        'Body': ParagraphStyle(
            'BodyText',
            parent=base_styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor("#374151"),
            spaceAfter=8
        ),
        'Bullet': ParagraphStyle(
            'BulletText',
            parent=base_styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor("#374151"),
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        ),
        'Blockquote': ParagraphStyle(
            'BlockquoteText',
            parent=base_styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor("#4b5563"),
            leftIndent=15,
            rightIndent=15,
            spaceBefore=8,
            spaceAfter=8
        ),
        'CodeBlock': ParagraphStyle(
            'CodeBlockText',
            parent=base_styles['Normal'],
            fontName='Courier',
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#0f172a"),
            leftIndent=10,
            rightIndent=10,
            spaceBefore=8,
            spaceAfter=8
        )
    }

    story = []
    
    # Title
    cleaned_title = clean_text_for_pdf(title)
    story.append(Paragraph(convert_markdown_inline(cleaned_title), styles['Title']))
    
    # Divider Line below title
    title_line = Table(
        [['']], 
        colWidths=[504], 
        rowHeights=[1]
    )
    title_line.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-1), 1.5, colors.HexColor("#2563eb")),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(title_line)
    story.append(Spacer(1, 15))
    
    # Parse Markdown blocks
    cleaned_content = clean_text_for_pdf(content)
    
    # Split content by markdown code blocks first to protect code blocks from splitlines formatting
    blocks = []
    code_block_pattern = re.compile(r'```(.*?)\n(.*?)```', re.DOTALL)
    
    last_idx = 0
    for match in code_block_pattern.finditer(cleaned_content):
        # Add preceding text block
        preceding = cleaned_content[last_idx:match.start()].strip()
        if preceding:
            blocks.append(('text', preceding))
        
        # Add code block
        code_text = match.group(2).strip()
        blocks.append(('code', code_text))
        last_idx = match.end()
        
    remaining = cleaned_content[last_idx:].strip()
    if remaining:
        blocks.append(('text', remaining))
        
    # Now process each block
    for block_type, block_val in blocks:
        if block_type == 'code':
            # Render code block in a light gray panel Table
            escaped_code = escape_html_entities(block_val)
            # Re-insert newlines using br/
            formatted_code = escaped_code.replace('\n', '<br/>').replace(' ', '&nbsp;')
            code_para = Paragraph(formatted_code, styles['CodeBlock'])
            
            # Put in a box
            panel = Table([[code_para]], colWidths=[504])
            panel.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(Spacer(1, 4))
            story.append(panel)
            story.append(Spacer(1, 8))
        else:
            # Stateful markdown line parser
            lines = block_val.split('\n')
            
            active_paragraph = []
            active_blockquote = []
            
            def flush_paragraph():
                if active_paragraph:
                    text = " ".join(active_paragraph).strip()
                    if text:
                        story.append(Paragraph(convert_markdown_inline(text), styles['Body']))
                    active_paragraph.clear()
            
            def flush_blockquote():
                if active_blockquote:
                    text = " ".join(active_blockquote).strip()
                    if text:
                        para_flow = Paragraph(convert_markdown_inline(text), styles['Blockquote'])
                        # Panel styled Table
                        panel = Table([[para_flow]], colWidths=[504])
                        panel.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f9fafb")),
                            ('LINELEFT', (0, 0), (0, -1), 3, colors.HexColor("#4a90e2")),
                            ('TOPPADDING', (0, 0), (-1, -1), 6),
                            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                            ('LEFTPADDING', (0, 0), (-1, -1), 10),
                            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                        ]))
                        story.append(Spacer(1, 4))
                        story.append(panel)
                        story.append(Spacer(1, 8))
                    active_blockquote.clear()
            
            for line in lines:
                stripped_line = line.strip()
                
                # Empty line
                if not stripped_line:
                    flush_paragraph()
                    flush_blockquote()
                    continue
                
                # Heading 1
                if stripped_line.startswith('# '):
                    flush_paragraph()
                    flush_blockquote()
                    h_text = stripped_line[2:].strip()
                    story.append(Paragraph(convert_markdown_inline(h_text), styles['H1']))
                # Heading 2
                elif stripped_line.startswith('## '):
                    flush_paragraph()
                    flush_blockquote()
                    h_text = stripped_line[3:].strip()
                    story.append(Paragraph(convert_markdown_inline(h_text), styles['H2']))
                # Heading 3
                elif stripped_line.startswith('### '):
                    flush_paragraph()
                    flush_blockquote()
                    h_text = stripped_line[4:].strip()
                    story.append(Paragraph(convert_markdown_inline(h_text), styles['H3']))
                # Blockquote
                elif stripped_line.startswith('>'):
                    flush_paragraph()
                    quote_part = stripped_line.lstrip('>').strip()
                    active_blockquote.append(quote_part)
                # List items (unordered)
                elif stripped_line.startswith('- ') or stripped_line.startswith('* '):
                    flush_paragraph()
                    flush_blockquote()
                    bullet_content = stripped_line[2:].strip()
                    story.append(Paragraph(f"&bull;&nbsp; {convert_markdown_inline(bullet_content)}", styles['Bullet']))
                # List items (ordered)
                elif re.match(r'^\d+\.\s', stripped_line):
                    flush_paragraph()
                    flush_blockquote()
                    num_match = re.match(r'^(\d+)\.\s(.*)', stripped_line)
                    num_str = num_match.group(1)
                    num_content = num_match.group(2).strip()
                    story.append(Paragraph(f"{num_str}.&nbsp; {convert_markdown_inline(num_content)}", styles['Bullet']))
                # Normal paragraph text continuation
                else:
                    flush_blockquote() # Transition from blockquote to normal text without blank line
                    active_paragraph.append(stripped_line)
            
            # Flush any remaining items
            flush_paragraph()
            flush_blockquote()

    # Build the document
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
